In [1]:
import numpy as np


In [2]:
import pandas as pd
df=pd.read_csv('Salary_Data.csv')

#df['Tran_Symptoms']= df['Most common symptoms'].apply(tran_symptoms)
#df['Tran_Severity']= df['Severity'].apply(tran_severity)
#df['Most common symptoms']= df['Most common symptoms'].apply(tran_symptoms)
#df['Severity']= df['Severity'].apply(tran_severity)

#print(df.dtypes)
df


YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [3]:
df.dtypes


YearsExperience    float64
Salary             float64
dtype: object

In [5]:
import numpy as np
x_exp=np.array(df['YearsExperience']).reshape(-1,1)
y_salary=np.array(df['Salary']).reshape(-1,1)
print(x_exp)
print(y_salary)

[[ 1.1]
 [ 1.3]
 [ 1.5]
 [ 2. ]
 [ 2.2]
 [ 2.9]
 [ 3. ]
 [ 3.2]
 [ 3.2]
 [ 3.7]
 [ 3.9]
 [ 4. ]
 [ 4. ]
 [ 4.1]
 [ 4.5]
 [ 4.9]
 [ 5.1]
 [ 5.3]
 [ 5.9]
 [ 6. ]
 [ 6.8]
 [ 7.1]
 [ 7.9]
 [ 8.2]
 [ 8.7]
 [ 9. ]
 [ 9.5]
 [ 9.6]
 [10.3]
 [10.5]]
[[ 39343.]
 [ 46205.]
 [ 37731.]
 [ 43525.]
 [ 39891.]
 [ 56642.]
 [ 60150.]
 [ 54445.]
 [ 64445.]
 [ 57189.]
 [ 63218.]
 [ 55794.]
 [ 56957.]
 [ 57081.]
 [ 61111.]
 [ 67938.]
 [ 66029.]
 [ 83088.]
 [ 81363.]
 [ 93940.]
 [ 91738.]
 [ 98273.]
 [101302.]
 [113812.]
 [109431.]
 [105582.]
 [116969.]
 [112635.]
 [122391.]
 [121872.]]


In [6]:
from sklearn.neighbors import KNeighborsClassifier

In [7]:
knn=KNeighborsClassifier(1)

In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_exp,y_salary,test_size=0.2)


In [9]:
type(x_train),type(y_train),y_train

(numpy.ndarray,
 numpy.ndarray,
 array([[ 64445.],
        [ 67938.],
        [ 83088.],
        [ 63218.],
        [ 39891.],
        [101302.],
        [ 81363.],
        [ 61111.],
        [ 98273.],
        [105582.],
        [ 60150.],
        [ 56642.],
        [ 46205.],
        [ 37731.],
        [ 39343.],
        [ 56957.],
        [ 93940.],
        [ 57189.],
        [ 55794.],
        [113812.],
        [ 54445.],
        [ 43525.],
        [ 91738.],
        [ 66029.]]))

In [10]:
y_train=y_train.ravel()
y_train

array([ 64445.,  67938.,  83088.,  63218.,  39891., 101302.,  81363.,
        61111.,  98273., 105582.,  60150.,  56642.,  46205.,  37731.,
        39343.,  56957.,  93940.,  57189.,  55794., 113812.,  54445.,
        43525.,  91738.,  66029.])

In [11]:
knn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=1)

In [12]:
x_test

array([[ 4.1],
       [ 9.5],
       [10.5],
       [ 9.6],
       [10.3],
       [ 8.7]])

In [13]:
predict=knn.predict(x_test)
predict

array([ 56957., 105582., 105582., 105582., 105582., 105582.])

In [14]:
predict

array([ 56957., 105582., 105582., 105582., 105582., 105582.])

In [15]:
y_test

array([[ 57081.],
       [116969.],
       [121872.],
       [112635.],
       [122391.],
       [109431.]])

In [16]:
score=knn.score(x_test,y_test)
score

0.0

In [18]:
from sklearn.metrics import confusion_matrix

In [19]:
predict,y_test

(array([ 56957., 105582., 105582., 105582., 105582., 105582.]),
 array([[ 57081.],
        [116969.],
        [121872.],
        [112635.],
        [122391.],
        [109431.]]))

In [20]:
confusion_matrix(y_test,predict)

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0]], dtype=int64)

In [21]:
predict=knn.predict(x_train)
predict

array([ 64445.,  67938.,  83088.,  63218.,  39891., 101302.,  81363.,
        61111.,  98273., 105582.,  60150.,  56642.,  46205.,  37731.,
        39343.,  56957.,  93940.,  57189.,  56957., 113812.,  64445.,
        43525.,  91738.,  66029.])

In [22]:
knn.score(x_train,y_train)

0.9166666666666666