In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_excel('PAML_COVID_Dataset.xlsx')

def tran_symptoms(x):
    if x=='dry cough':
        return 1
    if x=='tiredness':
        return 2
    if x=='fever':
        return 3
def tran_severity(b):
    if b=='Mild':
        return 4
    if b=='Moderate':
        return 5
    if b=='Seviour':
        return 6
#df['Tran_Symptoms']= df['Most common symptoms'].apply(tran_symptoms)
#df['Tran_Severity']= df['Severity'].apply(tran_severity)
df['Most common symptoms']= df['Most common symptoms'].apply(tran_symptoms)
df['Severity']= df['Severity'].apply(tran_severity)

#print(df.dtypes)
df


Date      Time              State/UnionTerritory  \
0                30/01/20  18:00:00                            Kerala   
1                31/01/20  18:00:00                            Kerala   
2     2020-01-02 00:00:00  18:00:00                            Kerala   
3     2020-02-02 00:00:00  18:00:00                            Kerala   
4     2020-03-02 00:00:00  18:00:00                            Kerala   
...                   ...       ...                               ...   
3130             17/06/20  08:00:00                           Tripura   
3131             17/06/20  08:00:00                       Uttarakhand   
3132             17/06/20  08:00:00                     Uttar Pradesh   
3133             17/06/20  08:00:00                       West Bengal   
3134             17/06/20  08:00:00  Cases being reassigned to states   

     ConfirmedIndianNational Gender  ConfirmedForeignNational  Age   \
0                          1   Male                         0     5   
1                          1  Female                        0     8   
2                          2   Male                         0    39   
3                          3  Female                        0    63   
4                          3   Male                         0     6   
...                      ...     ...                      ...   ...   
3130                       -   Male                         -    87   
3131                       -  Female                        -    78   
3132                       -   Male                         -    69   
3133                       -  Female                        -    80   
3134                       -  Female                        -    45   

                                 Serious symptoms  \
0     difficulty breathing or shortness of breath   
1                          chest pain or pressure   
2                      loss of speech or movement   
3                      loss of speech or movement   
4                          chest pain or pressure   
...                                           ...   
3130                       chest pain or pressure   
3131                       chest pain or pressure   
3132                   loss of speech or movement   
3133                       chest pain or pressure   
3134                       chest pain or pressure   

                                   Less common symptoms  Most common symptoms  \
0                                             diarrhoea                     3   
1                                           sore throat                     2   
2                                        conjunctivitis                     2   
3                                           sore throat                     2   
4     a rash on skin, or discolouration of fingers o...                     1   
...                                                 ...                   ...   
3130                                     conjunctivitis                     1   
3131  a rash on skin, or discolouration of fingers o...                     1   
3132                                     conjunctivitis                     3   
3133                                           headache                     2   
3134                             loss of taste or smell                     2   

      Severity Patient_Status   
0            6           Covid  
1            4             flu  
2            6             flu  
3            6           Covid  
4            5             flu  
...        ...             ...  
3130         4           Covid  
3131         6             flu  
3132         4             flu  
3133         4             flu  
3134         5           Covid  

[3135 rows x 12 columns]

In [3]:
df.dtypes


Date                        object
Time                        object
State/UnionTerritory        object
ConfirmedIndianNational     object
Gender                      object
ConfirmedForeignNational    object
Age                          int64
Serious symptoms            object
Less common symptoms        object
Most common symptoms         int64
Severity                     int64
Patient_Status              object
dtype: object

In [4]:

print(df['Most common symptoms'])
x_symptoms=np.array(df['Most common symptoms']).reshape(-1,1)
y_severity=np.array(df['Severity']).reshape(-1,1)
print(x_symptoms)
print(y_severity)

0       3
1       2
2       2
3       2
4       1
       ..
3130    1
3131    1
3132    3
3133    2
3134    2
Name: Most common symptoms, Length: 3135, dtype: int64
[[3]
 [2]
 [2]
 ...
 [3]
 [2]
 [2]]
[[6]
 [4]
 [6]
 ...
 [4]
 [4]
 [5]]


In [5]:
from sklearn.neighbors import KNeighborsClassifier

In [6]:
knn=KNeighborsClassifier(1)

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_symptoms,y_severity,test_size=0.2)


In [8]:
type(x_train),type(y_train),y_train

(numpy.ndarray,
 numpy.ndarray,
 array([[6],
        [6],
        [4],
        ...,
        [6],
        [6],
        [6]], dtype=int64))

In [9]:
y_train=y_train.ravel()
y_train

array([6, 6, 4, ..., 6, 6, 6], dtype=int64)

In [10]:
knn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=1)

In [11]:
x_test

array([[2],
       [1],
       [2],
       [3],
       [1],
       [2],
       [2],
       [1],
       [1],
       [2],
       [1],
       [3],
       [1],
       [1],
       [2],
       [2],
       [1],
       [1],
       [1],
       [3],
       [1],
       [3],
       [1],
       [2],
       [3],
       [1],
       [1],
       [3],
       [3],
       [1],
       [3],
       [3],
       [1],
       [1],
       [2],
       [3],
       [3],
       [1],
       [1],
       [1],
       [2],
       [3],
       [1],
       [3],
       [1],
       [1],
       [2],
       [2],
       [1],
       [2],
       [3],
       [3],
       [1],
       [3],
       [3],
       [2],
       [1],
       [1],
       [3],
       [3],
       [2],
       [2],
       [1],
       [2],
       [3],
       [2],
       [3],
       [3],
       [3],
       [2],
       [1],
       [3],
       [1],
       [3],
       [1],
       [3],
       [1],
       [1],
       [1],
       [3],
       [2],
       [3],
       [2],
    

In [12]:
predict=knn.predict(x_test)
predict

array([5, 5, 5, 4, 5, 5, 5, 5, 5, 5, 5, 4, 5, 5, 5, 5, 5, 5, 5, 4, 5, 4,
       5, 5, 4, 5, 5, 4, 4, 5, 4, 4, 5, 5, 5, 4, 4, 5, 5, 5, 5, 4, 5, 4,
       5, 5, 5, 5, 5, 5, 4, 4, 5, 4, 4, 5, 5, 5, 4, 4, 5, 5, 5, 5, 4, 5,
       4, 4, 4, 5, 5, 4, 5, 4, 5, 4, 5, 5, 5, 4, 5, 4, 5, 5, 5, 5, 5, 5,
       5, 4, 5, 5, 5, 4, 4, 5, 4, 4, 4, 4, 5, 5, 4, 4, 5, 5, 5, 5, 4, 5,
       5, 4, 5, 5, 5, 4, 5, 5, 5, 5, 4, 5, 5, 4, 5, 4, 5, 4, 5, 5, 4, 4,
       4, 5, 5, 5, 4, 5, 5, 5, 4, 5, 5, 5, 5, 5, 4, 4, 4, 5, 5, 5, 5, 4,
       5, 4, 4, 4, 4, 5, 5, 5, 5, 5, 4, 5, 5, 5, 4, 4, 4, 4, 5, 5, 5, 5,
       5, 5, 4, 5, 4, 5, 5, 4, 4, 5, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 4, 5,
       5, 5, 5, 5, 5, 4, 5, 5, 4, 5, 4, 4, 5, 4, 4, 5, 4, 5, 5, 4, 5, 4,
       4, 4, 5, 5, 5, 5, 4, 5, 5, 5, 5, 4, 5, 4, 4, 4, 5, 5, 5, 4, 5, 5,
       4, 5, 5, 4, 5, 4, 4, 4, 4, 5, 4, 5, 5, 5, 5, 4, 5, 4, 5, 4, 5, 5,
       5, 4, 5, 4, 5, 5, 4, 5, 5, 5, 4, 5, 5, 4, 5, 4, 5, 5, 4, 5, 5, 4,
       5, 4, 5, 4, 5, 5, 5, 5, 4, 4, 5, 4, 4, 5, 5,

In [13]:
predict

array([5, 5, 5, 4, 5, 5, 5, 5, 5, 5, 5, 4, 5, 5, 5, 5, 5, 5, 5, 4, 5, 4,
       5, 5, 4, 5, 5, 4, 4, 5, 4, 4, 5, 5, 5, 4, 4, 5, 5, 5, 5, 4, 5, 4,
       5, 5, 5, 5, 5, 5, 4, 4, 5, 4, 4, 5, 5, 5, 4, 4, 5, 5, 5, 5, 4, 5,
       4, 4, 4, 5, 5, 4, 5, 4, 5, 4, 5, 5, 5, 4, 5, 4, 5, 5, 5, 5, 5, 5,
       5, 4, 5, 5, 5, 4, 4, 5, 4, 4, 4, 4, 5, 5, 4, 4, 5, 5, 5, 5, 4, 5,
       5, 4, 5, 5, 5, 4, 5, 5, 5, 5, 4, 5, 5, 4, 5, 4, 5, 4, 5, 5, 4, 4,
       4, 5, 5, 5, 4, 5, 5, 5, 4, 5, 5, 5, 5, 5, 4, 4, 4, 5, 5, 5, 5, 4,
       5, 4, 4, 4, 4, 5, 5, 5, 5, 5, 4, 5, 5, 5, 4, 4, 4, 4, 5, 5, 5, 5,
       5, 5, 4, 5, 4, 5, 5, 4, 4, 5, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 4, 5,
       5, 5, 5, 5, 5, 4, 5, 5, 4, 5, 4, 4, 5, 4, 4, 5, 4, 5, 5, 4, 5, 4,
       4, 4, 5, 5, 5, 5, 4, 5, 5, 5, 5, 4, 5, 4, 4, 4, 5, 5, 5, 4, 5, 5,
       4, 5, 5, 4, 5, 4, 4, 4, 4, 5, 4, 5, 5, 5, 5, 4, 5, 4, 5, 4, 5, 5,
       5, 4, 5, 4, 5, 5, 4, 5, 5, 5, 4, 5, 5, 4, 5, 4, 5, 5, 4, 5, 5, 4,
       5, 4, 5, 4, 5, 5, 5, 5, 4, 4, 5, 4, 4, 5, 5,

In [14]:
y_test

array([[6],
       [4],
       [5],
       [6],
       [5],
       [6],
       [6],
       [6],
       [5],
       [5],
       [4],
       [4],
       [5],
       [6],
       [5],
       [4],
       [5],
       [6],
       [6],
       [5],
       [6],
       [5],
       [4],
       [5],
       [4],
       [4],
       [6],
       [6],
       [4],
       [4],
       [6],
       [4],
       [5],
       [4],
       [5],
       [6],
       [4],
       [4],
       [4],
       [6],
       [6],
       [6],
       [6],
       [5],
       [6],
       [6],
       [5],
       [6],
       [4],
       [5],
       [6],
       [5],
       [6],
       [6],
       [6],
       [5],
       [5],
       [4],
       [6],
       [6],
       [6],
       [4],
       [6],
       [6],
       [4],
       [6],
       [5],
       [5],
       [5],
       [6],
       [5],
       [4],
       [5],
       [5],
       [5],
       [5],
       [5],
       [4],
       [6],
       [6],
       [4],
       [4],
       [4],
    

In [15]:
score=knn.score(x_test,y_test)
score

0.34290271132376393

In [16]:
from sklearn.metrics import confusion_matrix

In [17]:
predict,y_test

(array([5, 5, 5, 4, 5, 5, 5, 5, 5, 5, 5, 4, 5, 5, 5, 5, 5, 5, 5, 4, 5, 4,
        5, 5, 4, 5, 5, 4, 4, 5, 4, 4, 5, 5, 5, 4, 4, 5, 5, 5, 5, 4, 5, 4,
        5, 5, 5, 5, 5, 5, 4, 4, 5, 4, 4, 5, 5, 5, 4, 4, 5, 5, 5, 5, 4, 5,
        4, 4, 4, 5, 5, 4, 5, 4, 5, 4, 5, 5, 5, 4, 5, 4, 5, 5, 5, 5, 5, 5,
        5, 4, 5, 5, 5, 4, 4, 5, 4, 4, 4, 4, 5, 5, 4, 4, 5, 5, 5, 5, 4, 5,
        5, 4, 5, 5, 5, 4, 5, 5, 5, 5, 4, 5, 5, 4, 5, 4, 5, 4, 5, 5, 4, 4,
        4, 5, 5, 5, 4, 5, 5, 5, 4, 5, 5, 5, 5, 5, 4, 4, 4, 5, 5, 5, 5, 4,
        5, 4, 4, 4, 4, 5, 5, 5, 5, 5, 4, 5, 5, 5, 4, 4, 4, 4, 5, 5, 5, 5,
        5, 5, 4, 5, 4, 5, 5, 4, 4, 5, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 4, 5,
        5, 5, 5, 5, 5, 4, 5, 5, 4, 5, 4, 4, 5, 4, 4, 5, 4, 5, 5, 4, 5, 4,
        4, 4, 5, 5, 5, 5, 4, 5, 5, 5, 5, 4, 5, 4, 4, 4, 5, 5, 5, 4, 5, 5,
        4, 5, 5, 4, 5, 4, 4, 4, 4, 5, 4, 5, 5, 5, 5, 4, 5, 4, 5, 4, 5, 5,
        5, 4, 5, 4, 5, 5, 4, 5, 5, 5, 4, 5, 5, 4, 5, 4, 5, 5, 4, 5, 5, 4,
        5, 4, 5, 4, 5, 5, 5, 5, 4, 4, 

In [18]:
confusion_matrix(y_test,predict)

array([[ 79, 137,   0],
       [ 59, 136,   0],
       [ 83, 133,   0]], dtype=int64)

In [19]:
predict=knn.predict(x_train)
predict

array([5, 4, 4, ..., 5, 5, 4], dtype=int64)

In [20]:
knn.score(x_train,y_train)

0.33931419457735246